# Generated by Django 5.2.9 on 2025-12-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicenote',
            name='encrypted_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voicenote',
            name='encrypted_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
