# Generated by Django 5.2.9 on 2025-12-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encrypted_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='encrypted_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(blank=True, help_text='Random salt for user data encryption', max_length=255, null=True),
        ),
    ]
